//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 9/17/2016 6:18:25 AM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "ApiControllerService_Enums.h"


@interface ApiControllerService : NSObject
{
}
@property SoapProtocolVersion soapVersion;
@property BOOL allowAutoRedirect;
@property BOOL enableDecompression;
@property (nonatomic, copy) NSString *userAgent;
@property BOOL unsafeAuthenticatedConnectionSharing;
@property BOOL useDefaultCredentials;
@property (nonatomic, copy) NSString *connectionGroupName;
@property BOOL preAuthenticate;
@property (nonatomic, copy) NSString *url;
@property int timeout;
@property (nonatomic, assign) void(*targetAction)(id target,id sender,NSString* xml);
@property (nonatomic,assign) id actionDelegate;
@property (nonatomic, strong) NSURLConnection *wsConnection;
@property (nonatomic, strong) NSMutableData *webData;
@property (nonatomic, strong) NSError *error;
@property (nonatomic, strong) NSMutableDictionary *requestHeaders;
@property (nonatomic, copy)   NSString *eventName;

///Origin Return Type:NSString
-(void)Followingdetails:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)limit :(NSString *)offset ;
///Origin Return Type:NSString
-(void)Confirmotp:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)otp :(NSString *)mob_no ;
///Origin Return Type:NSString
-(void)tos:(NSString *)api_username :(NSString *)api_password ;
///Origin Return Type:NSString
-(void)Followuser:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)follow_id ;
///Origin Return Type:NSString
-(void)Unfollowuser:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)follow_id ;
///Origin Return Type:NSString
-(void)Checkpromotion:(NSString *)api_username :(NSString *)api_password :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)helppage:(NSString *)api_username :(NSString *)api_password ;
///Origin Return Type:NSString
-(void)Getotp:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)mob_no :(NSString *)country_code ;
///Origin Return Type:NSString
-(void)braintreeClientToken:(NSString *)api_username :(NSString *)api_password ;
///Origin Return Type:NSString
-(void)processingPayment:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id :(NSString *)promotion_id :(NSString *)currency_code :(NSString *)pay_nonce ;
///Origin Return Type:NSString
-(void)Editprofile:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)fb_email :(NSString *)fb_firstname :(NSString *)fb_lastname :(NSString *)fb_phone :(NSString *)fb_profileurl :(NSString *)full_name :(NSString *)user_img :(NSString *)facebook_id :(NSString *)mobile_no :(NSString *)show_mobile_no ;
///Origin Return Type:NSString
-(void)Sendofferreq:(NSString *)api_username :(NSString *)api_password :(NSString *)sender_id :(NSString *)source_id :(NSString *)chat_id :(NSString *)created_date :(NSString *)message :(NSString *)offer_price ;
///Origin Return Type:NSString
-(void)pushsignout:(NSString *)api_username :(NSString *)api_password :(NSString *)deviceId ;
///Origin Return Type:NSString
-(void)getcoupon:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id ;
///Origin Return Type:NSString
-(void)createcoupon:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)coupon_value :(NSString *)type :(NSString *)item_id :(NSString *)start_date :(NSString *)end_date :(NSString *)status :(NSString *)max_amount ;
///Origin Return Type:NSString
-(void)couponstatus:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)coupon_id ;
///Origin Return Type:NSString
-(void)profile:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)user_name ;
///Origin Return Type:NSString
-(void)deleteproduct:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)searchbyitem:(NSString *)api_username :(NSString *)api_password :(NSString *)item_id :(NSString *)user_id ;
///Origin Return Type:NSString
-(void)productbeforeadd:(NSString *)api_username :(NSString *)api_password :(NSString *)lang_type ;
///Origin Return Type:NSString
-(void)getpromotion:(NSString *)api_username :(NSString *)api_password ;
///Origin Return Type:NSString
-(void)mypromotions:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)type ;
///Origin Return Type:NSString
-(void)notification:(NSString *)api_username :(NSString *)api_password :(NSString *)userId :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)getchatid:(NSString *)api_username :(NSString *)api_password :(NSString *)sender_id :(NSString *)receiver_id ;
///Origin Return Type:NSString
-(void)getchat:(NSString *)api_username :(NSString *)api_password :(NSString *)sender_id :(NSString *)receiver_id :(NSString *)type :(NSString *)source_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)sendchat:(NSString *)api_username :(NSString *)api_password :(NSString *)sender_id :(NSString *)chat_id :(NSString *)type :(NSString *)message :(NSString *)created_date :(NSString *)source_id ;
///Origin Return Type:NSString
-(void)applycoupon:(NSString *)api_username :(NSString *)api_password :(NSString *)coupon_code :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)shippingavail:(NSString *)api_username :(NSString *)api_password :(NSString *)shipping_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)Getlikedid:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id ;
///Origin Return Type:NSString
-(void)Getfollowerid:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id ;
///Origin Return Type:NSString
-(void)solditem:(NSString *)api_username :(NSString *)api_password :(NSString *)value :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)reportitem:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)resetbadge:(NSString *)api_username :(NSString *)api_password :(NSString *)deviceToken ;
///Origin Return Type:NSString
-(void)adddeviceid:(NSString *)api_username :(NSString *)api_password :(NSString *)deviceId :(NSString *)userid :(NSString *)devicetype :(NSString *)deviceToken :(NSString *)devicemode :(NSString *)lang_type ;
///Origin Return Type:NSString
-(void)Followersdetails:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)getcomments:(NSString *)api_username :(NSString *)api_password :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)getcountrycurrency:(NSString *)api_username :(NSString *)api_password ;
///Origin Return Type:NSString
-(void)postcomment:(NSString *)api_username :(NSString *)api_password :(NSString *)comment :(NSString *)user_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)getsettings:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id ;
///Origin Return Type:NSString
-(void)removeimage:(NSString *)api_username :(NSString *)api_password :(NSString *)type :(NSString *)name ;
///Origin Return Type:NSString
-(void)addproduct:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id :(NSString *)item_name :(NSString *)item_des :(NSString *)price :(NSString *)size :(NSString *)category :(NSString *)subcategory :(NSString *)chat_to_buy :(NSString *)exchange_to_buy :(NSString *)currency :(NSString *)lat :(NSString *)lon :(NSString *)address :(NSString *)shipping_time :(NSString *)remove_img :(NSString *)product_img :(NSString *)shipping_detail :(NSString *)item_condition :(NSString *)make_offer :(NSString *)instant_buy :(NSString *)paypal_id :(NSString *)shipping_cost :(NSString *)country_id ;
///Origin Return Type:NSString
-(void)messages:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)myexchanges:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)type ;
///Origin Return Type:NSString
-(void)createexchange:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)myitem_id :(NSString *)exchangeitem_id ;
///Origin Return Type:NSString
-(void)exchangestatus:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)exchange_id :(NSString *)status ;
///Origin Return Type:NSString
-(void)addShipping:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)full_name :(NSString *)nick_name :(NSString *)country_id :(NSString *)country_name :(NSString *)state :(NSString *)address1 :(NSString *)address2 :(NSString *)city :(NSString *)zip_code :(NSString *)phone_no :(NSString *)defaultaddress :(NSString *)shipping_id ;
///Origin Return Type:NSString
-(void)getShippingAddress:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)setdefaultshipping:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)shipping_id ;
///Origin Return Type:NSString
-(void)removeshipping:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)shipping_id ;
///Origin Return Type:NSString
-(void)gettrackdetails:(NSString *)api_username :(NSString *)api_password :(NSString *)order_id ;
///Origin Return Type:NSString
-(void)orderstatus:(NSString *)api_username :(NSString *)api_password :(NSString *)orderid :(NSString *)chstatus :(NSString *)subject :(NSString *)message :(NSString *)id :(NSString *)shippingdate :(NSString *)couriername :(NSString *)courierservice :(NSString *)trackid :(NSString *)notes ;
///Origin Return Type:NSString
-(void)Itemlike:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)buynowPayment:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)item_id :(NSString *)shipping_id :(NSString *)merchant_id :(NSString *)currency_code :(NSString *)nonce :(NSString *)item_price :(NSString *)shipping_fee :(NSString *)order_total ;
///Origin Return Type:NSString
-(void)myorders:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)mysales:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)orderdetails:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)order_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:
-(void)checking:(NSString *)user_id ;
///Origin Return Type:NSString
-(void)payment:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)shipping_id :(NSString *)item_id :(NSString *)quantity :(NSString *)size :(NSString *)coupon_id ;
///Origin Return Type:NSString
-(void)login:(NSString *)api_username :(NSString *)api_password :(NSString *)email :(NSString *)password ;
///Origin Return Type:NSString
-(void)signup:(NSString *)api_username :(NSString *)api_password :(NSString *)user_name :(NSString *)full_name :(NSString *)email :(NSString *)password ;
///Origin Return Type:NSString
-(void)sociallogin:(NSString *)api_username :(NSString *)api_password :(NSString *)type :(NSString *)id :(NSString *)first_name :(NSString *)last_name :(NSString *)email :(NSString *)image_url ;
///Origin Return Type:NSString
-(void)forgetpassword:(NSString *)api_username :(NSString *)api_password :(NSString *)email ;
///Origin Return Type:NSString
-(void)changepassword:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)old_password :(NSString *)new_password ;
///Origin Return Type:NSString
-(void)getcategory:(NSString *)api_username :(NSString *)api_password :(NSString *)lang_type ;
///Origin Return Type:NSString
-(void)getItems:(NSString *)api_username :(NSString *)api_password :(NSString *)type :(NSString *)price :(NSString *)search_key :(NSString *)category_id :(NSString *)subcategory_id :(NSString *)user_id :(NSString *)item_id :(NSString *)seller_id :(NSString *)sorting_id :(NSString *)offset :(NSString *)limit :(NSString *)lat :(NSString *)lon :(NSString *)posted_within :(NSString *)distance ;
///Origin Return Type:NSString
-(void)updateview:(NSString *)api_username :(NSString *)api_password :(NSString *)item_id ;
-(id) initWithTarget:(id)target  AndAction:(void(*)(id target,id sender ,NSString* xml))action;
-(void) addTarget:(id)target AndAction:(void(*)(id target,id sender ,NSString* xml))action;
///Origin Return Type:NSString
-(void)admindatas:(NSString *)api_username :(NSString *)api_password :(NSString *)lang_type ;
///Origin Return Type:NSString
-(void)getcountdetails:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id ;
///Origin Return Type:NSString
-(void)deletecomment:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)comment_id :(NSString *)item_id ;
///Origin Return Type:NSString
-(void)getreview:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)offset :(NSString *)limit ;
///Origin Return Type:NSString
-(void)updatereview:(NSString *)api_username :(NSString *)api_password :(NSString *)user_id :(NSString *)seller_id :(NSString *)review_id :(NSString *)rating :(NSString *)review_title :(NSString *)review_des :(NSString *)order_id ;
///Origin Return Type:NSString
-(void)checkItemstatus:(NSString *)api_username :(NSString *)api_password :(NSString *)item_id ;

@end
